services:
  backend:
    build: ./backend
    container_name: lab_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: labdb
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:16
    container_name: lab_db
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  frontend:
    build: ./frontend
    container_name: lab_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: